app.swagger_ui:
    path: /api
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger_json:
    path: /api/api_doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger, area: default }

app.swagger_ui_v1:
    path: /api/v1
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger_json_v1:
    path: /api/v1/api_doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger, area: default }
